#spring.application.name=Dictionary
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pract_db
    username: postgres
    password: PowerAndMotivation
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: changelogs/changelog-master.yaml
  springfox:
    documentation:
      swagger-ui:
        base-url: /api